steps:
  - id: deploy-function
    name: gcr.io/cloud-builders/gcloud
    dir: serverless-calendar/event
    args: ["functions",
           "deploy",
           "calendar_event_callback",
           "--runtime", "python37",
           "--project", "${PROJECT_ID}",
           "--region", "${_REGION}",
           "--set-env-vars", "SLACK_API_TOKEN=${_SLACK_API_TOKEN},SLACK_CHANNEL=${_SLACK_CHANNEL}",
           "--entry-point", "calendar_event_callback",
           "--trigger-http"
    ]
